# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nothing
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aremy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en

github_username:  aremy
googletag: G-VG0DMQCCRQ

author:
  name: aremy
  url: https://aremy.github.io
  twitter: aremy

twitter:
  username: aremy
  #card: summary
  card: summary_large_image

social:
  name: ARemy
  links:
    - https://twitter.com/aremy
    - https://github.com/aremy
    
# Build settings
markdown: kramdown
highlighter: rouge
# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: minima
date_format: "%b %-d, %Y"
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-avatar
  - jekyll-titles-from-headings

paginate: 1
paginate_path: "/blog/page:num/"

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/

#defaults:
#  - scope:
#      path: ""
#    values:
#      image: /assets/images/default-card.png